apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "airflow.fullname" . }}-cluster-access
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ template "airflow.name" . }}-scheduler
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
